/**
 * Shared Lucide icon set for the SmartHire application (front-office + back-office).
 *
 * Import `LUCIDE_ICONS` in any standalone component's `imports` array.
 *
 * Usage in templates:  <lucide-icon name="search" [size]="16"></lucide-icon>
 */
import { NgModule } from '@angular/core';
import {
  LucideAngularModule,
  LucideAngularComponent,
  LucideIconProvider,
  LUCIDE_ICONS as LUCIDE_ICONS_TOKEN,
  Activity,
  AlertCircle,
  Archive,
  ArrowLeft,
  ArrowRight,
  BarChart2,
  Bell,
  Bookmark,
  BookOpen,
  BrainCircuit,
  Briefcase,
  Calendar,
  ChartBar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CirclePlay,
  CircleQuestionMark,
  CircleX,
  Clock,
  Code,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  EllipsisVertical,
  Eye,
  EyeOff,
  File,
  FileText,
  Film,
  Flag,
  Flame,
  Folder,
  Github,
  Globe,
  GraduationCap,
  Grid2x2,
  HardDrive,
  Image,
  Info,
  Inbox,
  Layers,
  LayoutGrid,
  ListChecks,
  Lightbulb,
  Link,
  Linkedin,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  MessageSquare,
  Mic,
  Moon,
  Palette,
  Play,
  PlayCircle,
  Plus,
  Radio,
  RefreshCw,
  Route,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  SquarePen,
  Star,
  StarHalf,
  Sun,
  TrendingDown,
  TrendingUp,
  Trash2,
  TriangleAlert,
  Trophy,
  Twitter,
  Upload,
  User,
  Users,
  Loader,
  Sparkles,
  Wand2,
  X,
  Zap,
} from 'lucide-angular';

const icons = {
  Activity, AlertCircle, Archive, ArrowLeft, ArrowRight,
  BarChart2, Bell, Bookmark, BookOpen,
  BrainCircuit, Briefcase, Calendar, ChartBar, Check, CheckCircle,
  ChevronDown, ChevronLeft, ChevronRight, ChevronUp,
  CircleCheck, CirclePlay, CircleQuestionMark, CircleX,
  Clock, Code, Cpu, CreditCard, Database, DollarSign, Download, EllipsisVertical,
  Eye, EyeOff, File, FileText, Film, Flag, Flame, Folder,
  Github, Globe, GraduationCap, Grid2x2, HardDrive, Image, Info, Inbox,
  Layers, LayoutGrid, ListChecks, Lightbulb, Link, Linkedin,
  Lock, LogOut, Mail, Map, MapPin, MessageSquare, Mic, Moon,
  Palette, Play, PlayCircle, Plus, Radio, RefreshCw, Route, Search,
  Send, Server, Settings, Settings2, Shield, ShieldCheck, SquarePen,
  Star, StarHalf, Sun,
  TrendingDown, TrendingUp, Trash2, TriangleAlert, Trophy,
  Twitter, Upload, User, Users,
  Wand2, X, Zap, Sparkles, Loader,
};

/**
 * Wrapper NgModule that registers Lucide icons and re-exports the
 * LucideAngularComponent.  Standalone components import this class
 * instead of using LucideAngularModule.pick() (which returns
 * ModuleWithProviders — rejected by Angular 18 standalone imports).
 */
@NgModule({
  imports:    [LucideAngularModule],
  exports:    [LucideAngularModule],
  providers:  [
    { provide: LUCIDE_ICONS_TOKEN, multi: true, useValue: new LucideIconProvider(icons) },
  ],
})
export class LUCIDE_ICONS {}
