import { NgModule } from '@angular/core';
import {
  LucideAngularModule,
  LUCIDE_ICONS as LUCIDE_ICONS_TOKEN,
  LucideIconProvider,
  // importer Loader
  Loader,
  Activity,
  AlertCircle,
  Archive,
  ArrowLeft,
  ArrowRight,
  BarChart2,
  Bell,
  Bookmark,
  BookOpen,
  BrainCircuit,
  Briefcase,
  Calendar,
  ChartBar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CirclePlay,
  CircleQuestionMark,
  CircleX,
  Clock,
  Code,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  EllipsisVertical,
  Eye,
  EyeOff,
  File,
  FileText,
  Film,
  Flag,
  Flame,
  Folder,
  Github,
  Globe,
  GraduationCap,
  Grid2x2,
  HardDrive,
  Image,
  Info,
  Inbox,
  Layers,
  LayoutGrid,
  ListChecks,
  Lightbulb,
  Link,
  Linkedin,
  Lock,
  LogOut,
  Mail,
  Map,
  MapPin,
  MessageSquare,
  Mic,
  Moon,
  Palette,
  Play,
  PlayCircle,
  Plus,
  Radio,
  RefreshCw,
  Route,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  SquarePen,
  Star,
  StarHalf,
  Sun,
  TrendingDown,
  TrendingUp,
  Trash2,
  TriangleAlert,
  Trophy,
  Twitter,
  Upload,
  User,
  Users,
  Loader,
  Sparkles,
  Wand2,
  X,
  Zap,
} from 'lucide-angular';

// ✅ Ajouter Loader dans l'objet icons
const icons = {
<<<<<<< HEAD
  Activity, AlertCircle, Archive, ArrowLeft, ArrowRight,
  BarChart2, Bell, Bookmark, BookOpen,
  BrainCircuit, Briefcase, Calendar, ChartBar, Check, CheckCircle,
  ChevronDown, ChevronLeft, ChevronRight, ChevronUp,
  CircleCheck, CirclePlay, CircleQuestionMark, CircleX,
=======
  Loader, // <-- ajouté
  Activity, Archive, ArrowLeft, ArrowRight, Bell, Bookmark, BookOpen,
  BrainCircuit, Briefcase, Calendar, ChartBar, Check, ChevronDown, ChevronLeft,
  ChevronRight, ChevronUp, CircleCheck, CirclePlay, CircleQuestionMark, CircleX,
>>>>>>> feature/event-management
  Clock, Code, Cpu, CreditCard, Database, DollarSign, Download, EllipsisVertical,
  Eye, EyeOff, File, FileText, Film, Flag, Flame, Folder,
  Github, Globe, GraduationCap, Grid2x2, HardDrive, Image, Info, Inbox,
  Layers, LayoutGrid, ListChecks, Lightbulb, Link, Linkedin,
  Lock, LogOut, Mail, Map, MapPin, MessageSquare, Mic, Moon,
  Palette, Play, PlayCircle, Plus, Radio, RefreshCw, Route, Search,
  Send, Server, Settings, Settings2, Shield, ShieldCheck, SquarePen,
  Star, StarHalf, Sun,
  TrendingDown, TrendingUp, Trash2, TriangleAlert, Trophy,
  Twitter, Upload, User, Users,
  Wand2, X, Zap, Sparkles, Loader,
};

/**
 * Module partagé pour Lucide Angular.
 * Les composants standalone importent ce module au lieu de LucideAngularModule.pick()
 */
@NgModule({
  imports: [LucideAngularModule],
  exports: [LucideAngularModule],
  providers: [
    {
      provide: LUCIDE_ICONS_TOKEN,
      multi: true,
      useValue: new LucideIconProvider(icons),
    },
  ],
})
export class LUCIDE_ICONS {}