import { NgModule } from '@angular/core';
import {
  LucideAngularModule,
  LUCIDE_ICONS as LUCIDE_ICONS_TOKEN,
  LucideIconProvider,
  // importer Loader
  Loader,
  Activity,
  Archive,
  ArrowLeft,
  ArrowRight,
  Bell,
  Bookmark,
  BookOpen,
  BrainCircuit,
  Briefcase,
  Calendar,
  ChartBar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CirclePlay,
  CircleQuestionMark,
  CircleX,
  Clock,
  Code,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  EllipsisVertical,
  Eye,
  EyeOff,
  File,
  FileText,
  Film,
  Flag,
  Folder,
  Github,
  Globe,
  GraduationCap,
  Grid2x2,
  HardDrive,
  Image,
  Info,
  Layers,
  LayoutGrid,
  Lightbulb,
  Link,
  Linkedin,
  Lock,
  LogOut,
  Mail,
  MapPin,
  MessageSquare,
  Play,
  Plus,
  Radio,
  RefreshCw,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  SquarePen,
  Star,
  StarHalf,
  TrendingDown,
  TrendingUp,
  Trash2,
  TriangleAlert,
  Twitter,
  Upload,
  User,
  Users,
  X,
  Zap,
} from 'lucide-angular';

// ✅ Ajouter Loader dans l'objet icons
const icons = {
  Loader, // <-- ajouté
  Activity, Archive, ArrowLeft, ArrowRight, Bell, Bookmark, BookOpen,
  BrainCircuit, Briefcase, Calendar, ChartBar, Check, ChevronDown, ChevronLeft,
  ChevronRight, ChevronUp, CircleCheck, CirclePlay, CircleQuestionMark, CircleX,
  Clock, Code, Cpu, CreditCard, Database, DollarSign, Download, EllipsisVertical,
  Eye, EyeOff, File, FileText, Film, Flag, Folder, Github, Globe, GraduationCap,
  Grid2x2, HardDrive, Image, Info, Layers, LayoutGrid, Lightbulb, Link, Linkedin,
  Lock, LogOut, Mail, MapPin, MessageSquare, Play, Plus, Radio, RefreshCw, Search,
  Send, Server, Settings, Shield, ShieldCheck, SquarePen, Star, StarHalf,
  TrendingDown, TrendingUp, Trash2, TriangleAlert, Twitter, Upload, User, Users,
  X, Zap,
};

/**
 * Module partagé pour Lucide Angular.
 * Les composants standalone importent ce module au lieu de LucideAngularModule.pick()
 */
@NgModule({
  imports: [LucideAngularModule],
  exports: [LucideAngularModule],
  providers: [
    {
      provide: LUCIDE_ICONS_TOKEN,
      multi: true,
      useValue: new LucideIconProvider(icons),
    },
  ],
})
export class LUCIDE_ICONS {}